apiVersion: v1
kind: Service
metadata:
  name: journal-frontend
  namespace: journal
spec:
  ports:
    - port: 80
  selector:
    app: journal-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: journal-frontend
  namespace: journal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: journal-frontend
  template:
    metadata:
      labels:
        app: journal-frontend
    spec:
      containers:
        - name: journal-frontend
          image: journal-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            # Frontend pratar direkt med services i klustret
            - name: VITE_AUTH_BASE_URL
              value: "http://auth-service:8081"
            - name: VITE_PATIENT_BASE_URL
              value: "http://patient-service:8082"
            - name: VITE_MESSAGE_BASE_URL
              value: "http://message-service:8083"
